matrix voice support
MycroftAI/enclosure-picroft pull request #84
Opened 2018-12-04 05:42 UTC by LearnedVector

* Description of what the PR does, such as fixes # {issue number}
This adds support for Matrix Voice or Matrix Creator.
https://www.matrix.one/

* Description of how to validate or test this PR
follow the auto_run setup prompt to install Matrix Voice.

* Whether you have signed a CLA (Contributor Licensing Agreement)
Yes

2018-12-04 06:31 UTC, penrods requested changes
Looking good!  I tossed in some edits of prompts, nothing major.  I'd like to walk through the process myself, also, to see how it feels.

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
>          echo -n "Choice [1-4]: "
Change to "1-5"

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "This will require 3 reboots"
echo "This process is automatic, but requires rebooting three times.  Please be patient!"

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "Add Matrix repo and key and Update and install packages"
echo "Adding Matrix repo and installing packages..."

No need for all that detail.

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "Needs to reboot in case of kernel updates"
echo "Rebooting to apply kernel updates, the installation will resume afterwards"

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "installing matcixio-kernel-modules"
echo "Installing matrixio-kernel-modules..."

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "Need to reboot after installing matcixio-kernel-modules and pulseaudio"
echo "Rebooting to apply audio subsystem changes, the installation will continue afterwards."

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "setting Matrix as standard microphone..."
echo "Setting ...

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        echo "updating the python virtual environment"
echo "Updating

2018-12-04 06:31 UTC, penrods commented on home/pi/auto_run.sh
> +        read -p "Press enter to continue reboot! this should be the last one"
read -p "Your Matrix microphone is now setup!  Press enter to perform the final reboot and start Mycroft."

2018-12-04 18:08 UTC, LearnedVector commented
@penrods updated the prompts ^^

2018-12-14 04:13 UTC, LexiconCode commented
I just wanted to show my support. I'm looking forward to merge :)

2018-12-17 17:49 UTC, merged